### ISSUE TITLE
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`)

### ISSUE THREAD

**Issue by merolaika** [StephanAkkerman/liquidations-chart#3]
Hello, i get this error can help please?

python src/main.py
Downloading files: 100%|█████████████████████████████████████████████████████████████| 281/281 [00:33<00:00,  8.43it/s]
Downloaded 281 new files.
Traceback (most recent call last):
  File "C:\MeroKripto\liquidations-chart\src\main.py", line 6, in <module>
    show_plot(coin=COIN, market=MARKET)
  File "C:\MeroKripto\liquidations-chart\src\plot.py", line 210, in show_plot
    liquidations_plot(df[-180:])
  File "C:\MeroKripto\liquidations-chart\src\plot.py", line 143, in liquidations_plot
    ax2.plot(df_price.index, df_price, color="#edba35", label="BTC Price")
  File "C:\MeroKripto\liquidations-chart\venv\lib\site-packages\matplotlib\axes\_axes.py", line 1632, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "C:\MeroKripto\liquidations-chart\venv\lib\site-packages\matplotlib\axes\_base.py", line 312, in __call__
    yield from self._plot_args(this, kwargs)
  File "C:\MeroKripto\liquidations-chart\venv\lib\site-packages\matplotlib\axes\_base.py", line 487, in _plot_args
    x = _check_1d(xy[0])
  File "C:\MeroKripto\liquidations-chart\venv\lib\site-packages\matplotlib\cbook\__init__.py", line 1327, in _check_1d
    ndim = x[:, None].ndim
  File "C:\MeroKripto\liquidations-chart\venv\lib\site-packages\pandas\core\indexes\base.py", line 5199, in __getitem__
    disallow_ndim_indexing(result)
  File "C:\MeroKripto\liquidations-chart\venv\lib\site-packages\pandas\core\indexers\utils.py", line 343, in disallow_ndim_indexing
    raise ValueError(
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.

**Comment by StephanAkkerman** [comment]
@merolaika Can you try again with the latest requirements.txt?

**Comment by merolaika** [comment]
new requirements is working thanks

matplotlib==3.9.0
requests==2.32.3
pandas==2.2.2
tqdm==4.66.4
